import dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

/**
 * Load .env file if it exists (local development only)
 *
 * In local development, .env file is generated by the CLI and contains SECRETS_PROVIDER.
 * In cloud/pipelines, platform sets environment variables directly (no .env file needed).
 *
 * Skips loading if SECRETS_PROVIDER is already set (cloud/pipeline environments).
 * Walks up directory tree to find .env (similar to how .secrets.local.json is found).
 * Silently ignores if .env doesn't exist - that's expected in cloud environments.
 * Does NOT overwrite existing environment variables (platform vars take precedence).
 */
export function loadEnvIfExists(): void {
  // Skip if SECRETS_PROVIDER is already set (cloud/pipeline environment)
  if (process.env.SECRETS_PROVIDER) {
    return;
  }

  let currentDir = process.cwd();
  const maxDepth = 10;
  let depth = 0;

  while (depth < maxDepth) {
    const envPath = path.join(currentDir, '.env');

    if (fs.existsSync(envPath)) {
      // Check if this .env file contains SECRETS_PROVIDER
      // (Service-level .env files may only contain DATABASE_URL for Prisma Studio)
      const envContent = fs.readFileSync(envPath, 'utf-8');
      const hasSecretsProvider = envContent.includes('SECRETS_PROVIDER=');

      if (hasSecretsProvider) {
        dotenv.config({ path: envPath });
        return;
      }
      // Otherwise, continue searching up the directory tree
    }

    const parentDir = path.dirname(currentDir);
    if (parentDir === currentDir) {
      break; // Reached filesystem root
    }

    currentDir = parentDir;
    depth++;
  }

  // .env not found - OK in cloud/pipeline environments
  // Platform will have set env vars directly
}
